[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  included_files = ["netlify/functions/**"]
  
[context.production]
  [context.production.environment]
    NETLIFY_BLOBS_CONTEXT = "production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer-when-downgrade"